"""empty message

Revision ID: 0d1b03493784
Revises: 4564a828be39
Create Date: 2022-05-29 19:15:48.263838

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0d1b03493784'
down_revision = '4564a828be39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updated', mysql.DATETIME(), nullable=False))
    # ### end Alembic commands ###
