"""empty message

Revision ID: 67d23a35a6ac
Revises: 0d1b03493784
Create Date: 2022-05-29 19:16:16.575687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67d23a35a6ac'
down_revision = '0d1b03493784'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updated', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated')
    # ### end Alembic commands ###
